### ISSUE TITLE
Support .NET Framework

### ISSUE THREAD

**Issue by cmeeren** [AArnott/Xunit.Combinatorial#10]
I'd like to see support for .NET Framework. Currently, when installing the package (.NET Standard) in a .NET Framework project, it installs tons of dependencies (.NET Standard stuff). I'm sure that just by targeting .NET Framework too, most if not all of them could be eliminated.

I think it's just a matter of editing a few things in the csproj file.

(FYI: .NET Standard test projects doesn't play well with ReSharper, that's why I need this.)

**Comment by cmeeren** [comment]
Note that this is an actual problem, not simply a matter of "living with all the .NET Standard packages". When I installed Xunit.Combinatorial into a .NET Framework test project, all the .NET Standard packages immediately broke quite a few tests (relating to some System.Web stuff).

I've made a very simple PR that adds support for .NET 4.5. Tested and verified.

**Comment by AArnott** [comment]
Closed with fa9f00a
