### ISSUE TITLE
Add support for xunit.v3

### ISSUE THREAD

**Issue by dkokotov** [AArnott/Xunit.Combinatorial#113]
xUnit V3 has been released on 2024-12-16. Release announcement: https://xunit.net/releases/v3/1.0.0

**Comment by AArnott** [comment]
Go get v2.0.5-alpha from nuget.org and let me know how it goes.

**Comment by caleblloyd** [comment]
> Go get v2.0.5-alpha from nuget.org and let me know how it goes.

This worked for me when upgrading to `xunit.v3`.  Thanks!

**Comment by silkfire** [comment]
When can we expect the non-alpha release?

**Comment by AArnott** [comment]
I started the work to release it yesterday. It should be out very soon today.

**Comment by silkfire** [comment]
Awesome, thank you for the swift response 🎉

**Comment by 0xced** [comment]
It's probably too late (although Xunit.Combinatorial 2.0.24 could be unlisted form NuGet) but I think it would have been better to release a new package that targets xunit.v3. That's the path many packages followed while still keeping a package for v2 around.

* https://www.nuget.org/packages/MartinCostello.Logging.XUnit.v3
* https://www.nuget.org/packages/Meziantou.Extensions.Logging.Xunit.v3
* https://www.nuget.org/packages/Testcontainers.XunitV3
* https://www.nuget.org/packages/Verify.XunitV3

**Comment by AArnott** [comment]
I can't publish a new package id that starts with xunit, so it would have a very different name.
It works though... I just maintain 2 major versions.
