### ISSUE TITLE
How can I use this alongside a library that provides mocks

### ISSUE THREAD

**Issue by srivathsah** [AArnott/Xunit.Combinatorial#12]
Hi,

This is an immensely useful library from what I can see, however I cannot see a way of using it alongside a library that provides mocks as input of the test method eg:. AutoFixture with AutoMoq . I have a scenario where I need to write unit tests with test cases comprising of mocks and combinatorial data. I assume this is a common use case for many. Am I missing something ?

**Comment by AArnott** [comment]
Can you elaborate on what the problem is? What prevents you from using mocks when you are also using combinatorial data as inputs to your test method?

**Comment by AArnott** [comment]
Closing due to no response.
