### ISSUE TITLE
Support range of values

### ISSUE THREAD

**Issue by skarllot** [AArnott/Xunit.Combinatorial#18]
Create an attribute to specify a range of values:

```csharp
[Theory, CombinatorialData]
public void Copy_ToAnotherArray_CopyAllElements(
    [ValuesInRange(1, 10)] int length)
{
```

**Comment by sharwell** [comment]
This would allow Xunit.Combinatorial to replace [`[IterationData]`](https://github.com/dotnet/roslyn/blob/6a14f2675da380cc107070fc0783737159672b7d/src/VisualStudio/IntegrationTest/TestUtilities/IterationDataAttribute.cs).
