### ISSUE TITLE
ValuesUtilities.GetValuesFor(Type) should support Nullable<T>

### ISSUE THREAD

**Issue by sharwell** [AArnott/Xunit.Combinatorial#23]
It shouldn't be necessary to specify `[CombinatorialValues]` for a parameter of type `T?` when it is not required to specify values for the same parameter of type `T`. When `T?` is encountered, the values should be the union of `GetValuesFor(typeof(T))` and `null`.

**Comment by chwarr** [comment]
I think I have this implemented. I started [PR #24](https://github.com/AArnott/Xunit.Combinatorial/pull/24) with my proposed additions.

**Comment by AArnott** [comment]
This is available on nuget.org as 1.4.1 now. Thanks, @chwarr.
