### ISSUE TITLE
CombinatorialMemberData not recognized

### ISSUE THREAD

**Issue by drvic10k** [AArnott/Xunit.Combinatorial#40]
CombinatorialMemberData attribute is not found

this is copied from the readme into my code and for some reason, the parameter attribute is not found :

![image](https://user-images.githubusercontent.com/3754571/169547634-733d1f87-d1bd-4d2a-80bb-5c89a11eb486.png)

**Comment by AArnott** [comment]
CombinatorialMemberData was introduced in 1.5.2-beta. My guess is you're using the 1.4 version.

**Comment by drvic10k** [comment]
you are right, I am using the nuget version
