### ISSUE TITLE
Removed license notice in PairwiseStrategy.cs

### ISSUE THREAD

**Issue by TSRBerry** [AArnott/Xunit.Combinatorial#78]
While looking through this repository I noticed that the license information of [src/Xunit.Combinatorial/PairwiseStrategy.cs](https://github.com/AArnott/Xunit.Combinatorial/blob/main/src/Xunit.Combinatorial/PairwiseStrategy.cs) was mistakenly removed.

This is the commit that deleted the old information: https://github.com/AArnott/Xunit.Combinatorial/commit/0bdfb4fe87d6edb8dfa9cb91cc09184b7c52f3c7

Could you add it back?

**Comment by AArnott** [comment]
Oh, good catch. It definitely deserves to be brought back. Thank you.
