### ISSUE TITLE
Support for .NETCoreApp,Version

### ISSUE THREAD

**Issue by jovanpop-msft** [AArnott/Xunit.Combinatorial#8]
I cannot restore nugget package in dotnet core app:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1002	The dependency Xunit.Combinatorial 1.1.20 does not support framework .NETCoreApp,Version=v1.0.

Any plans to support it?

**Comment by AArnott** [comment]
Fixed in 781bfce5
