### ISSUE TITLE
ClassData support

### ISSUE THREAD

**Issue by kimsey0** [AArnott/Xunit.Combinatorial#94]
It would be nice to have support for [ClassData](https://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/#using-a-dedicated-data-class-with-classdata-), specifically for use with the typed [TheoryData](https://andrewlock.net/creating-strongly-typed-xunit-theory-test-data-with-theorydata/#using-theorydata-with-the-classdata-attribute) class. I imagine it would take the form of a new `CombinatorialClassDataAttribute`.

**Comment by AArnott** [comment]
I wonder why `ClassData` is better than `MemberData`. I haven't read the whole document.

Either of these are tasked with providing _all_ test case inputs, so there isn't room to create combinations of values as this library does. 
If you were thinking of something like expanding `CombinatorialValuesAttribute` to allow the values to come from a member or class though, that might be something new and doable.

**Comment by kimsey0** [comment]
I just like the strongly typed `TheoryData` class which allows me to have a `TheoryData<int, string, Guid>` instead of an `IEnumerable<object[]>`. I have only used it with `ClassData`, not with `MemberData`, but now that I re-read Andrew Lock's articles, I see that it can actually also be used with `MemberData`.

In any case, you right that `TheoryData` providing all test case inputs means it doesn't make sense for providing values for one parameter, as `CombinatorialValuesAttribute` does. I didn't think this issue through, so I'll close it.
